spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: todo-app
  datasource:
    url: jdbc:mysql://localhost:3306/todo_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:placeholder_id}
            client-secret: ${GOOGLE_CLIENT_SECRET:placeholder_secret}
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          github:
            client-id: ${GITHUB_CLIENT_ID:placeholder_id}
            client-secret: ${GITHUB_CLIENT_SECRET:placeholder_secret}
            scope: read:user, user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

app:
  jwt:
    secret: ${JWT_SECRET:very_secret_key_that_should_be_long_enough_for_hs256_at_least_32_bytes}
    expiration-ms: 86400000 # 1 day
